### ISSUE TITLE
Something weird with tags

### ISSUE THREAD

**Issue by ChristopherDavenport** [olafurpg/sbt-ci-release#101]
I just cut 0.4.0, and it released tag 0.3.1

https://travis-ci.com/ChristopherDavenport/circuit/jobs/286904804

Something there may be up, looking into it now.

**Comment by softinio** [comment]
We just experienced the same issue when publishing snapshot releases. Interesting!

Going to dig in more detail. Will update my findings here.

**Comment by olafurpg** [comment]
Thank you for reporting! Please reopen if this is still an issue.
