### ISSUE TITLE
clean somehow results in empty jarfiles

### ISSUE THREAD

**Issue by tpolecat** [olafurpg/sbt-ci-release#105]
We have [a project](https://github.com/gemini-hlsw/gsp-math) which publishes for JVM/JS and Scala 2.12/2.13 and with v1.5.2 of the plugin the 2.13 jarfiles are always empty! Nothing but a manifest. Works fine with v.1.5.0.

It seems that this commit https://github.com/olafurpg/sbt-ci-release/commit/5f0ca4509f4f0161168220cec7776df592daf7dd causes the classfiles to get wiped out prior to 2.13 packaging. I don't understand this thing well enough to explain how that's possible but it seems to be what's happening. Possibly something happening concurrently and it's nondeterministic but probable?

**Comment by olafurpg** [comment]
Thank you for reporting! This is an odd issue. Looks like the right thing to do is to release a revert first.

**Comment by tpolecat** [comment]
I'm surprised nobody else has reported, which makes me suspicious there's some other weird interaction in my build that's exposing it. I would definitely try to repro before reverting.

**Comment by olafurpg** [comment]
`ci-release` is kind of an alias for doing
```
clean
sonatypeBundleClean
+publishSigned
soatypeBundleRelease
```

You can try to do that locally (although note that it triggers a proper release)

**Comment by tpolecat** [comment]
Uh, well rolling back to 1.5.0 now the 2.12 jarfiles are empty. So there's some interaction between updates to sbt, sbt-ci-release, and/or sbt-scalajs-crossproject because all three have changed since the last successful cross-build. I will investigate more and report back.

**Comment by softinio** [comment]
@tpolecat if helpful to your investigation I have 1.5.0 working on multiple projects as expected with no issue with the only difference being you are using crossproject and I am not so totally you are probably right in looking into this area. 

Let me know if I can be of further help.

**Comment by olafurpg** [comment]
I opened https://github.com/gemini-hlsw/gsp-math/pull/71 disabling the publish step for the root project. It's not obvious at all that `skip in publish` is needed on the toplevel build.

I wish sbt would stop supporting the implicit "root" project. It used to be more common to use the root project but today I feel like most builds are multi-module and my impression is that the root project causes more confusion and harm than good.

**Comment by olafurpg** [comment]
We should try to improve the documentation or error handling somehow to prevent this from happening. It should be possible to detect the scenario when the root project conflicts with the module name of another project.

**Comment by olafurpg** [comment]
When I think of it, maybe sbt-ci-release should set `skip in publish := true` for all root projects 🤔 It's a better default IMO to assume there is no publishable module in the root project

**Comment by cb372** [comment]
> When I think of it, maybe sbt-ci-release should set `skip in publish := true` for all root projects 🤔 It's a better default IMO to assume there is no publishable module in the root project

That sounds like a reasonable default, but only if it's a multi-module project. Otherwise the root project is the one and only project you want to publish.

**Comment by tpolecat** [comment]
To me this seems like a bug in sbt. It should not allow multiple projects to have the same name.

**Comment by tpolecat** [comment]
In any case thanks @olafurpg, your PR fixed it. No problem with ci-release as far as I know, sorry for the trouble.
