### ISSUE TITLE
Issue publishing releases using Github Actions

### ISSUE THREAD

**Issue by worace** [olafurpg/sbt-ci-release#110]
Hi there -

I'm trying to use this plugin to publish a library via Github Actions. I think things are almost working, but I am running into an error toward the end of the pipeline which is causing my "release" jobs to fail.

I based the configuration for my release step ([source](https://github.com/worace/circe-geojson/blob/master/.github/workflows/release.yml)) on the ones in the sbt-ci-release repository, since it is also publishing using Github actions. Overall the docs have been great and that was a nice example to be able to look at.

My release step is failing with an error like this:

```
[info] Creating a staging repository in profile works.worace with a description key: [sbt-sonatype] circe-geojson-core 0.0.1-CI-2-SNAPSHOT
[info] Created successfully: worksworace-1007
[error] java.io.IOException: Supplied file /home/runner/work/circe-geojson/circe-geojson/target/sonatype-staging/0.0.1-CI-3-SNAPSHOT is a not an existing directory!
[error] Use 'last' for the full log.
##[error]Process completed with exit code 1.
```

It seems that the last step it succeeds on before that message is something inside of sbt-sonatype ([here](https://github.com/xerial/sbt-sonatype/blob/3d468407c927782a8773bb53e03370e6cf960b16/src/main/scala/xerial/sbt/sonatype/SonatypeClient.scala#L125)), so it's possible I'm running into an issue with sbt-sonatype or with how this plugin interacts with that one.

What's interesting is that the packages _do_ seem to actually get published. For example you can see a snapshot [here](https://oss.sonatype.org/content/repositories/snapshots/works/worace/circe-geojson-core_2.12/0.0.1-CI-3-SNAPSHOT/) that was published from github actions in [this build](https://github.com/worace/circe-geojson/runs/574446148?check_suite_focus=true). So even though the process is failing, the jars are getting to sonatype.

Additionally, I seem to be able to run `sbt ci-release` locally without errors (after configuring the appropriate ENV variables on my machine). [Here](https://gist.github.com/worace/a9153438e734121330c5fba3735c78d5) is an example log from running that process locally.

Finally, I should note that the auto-generated versions that sbt-ci-release publishes on every commit to master are also working. You can see in the SNAPSHOTS Repo here: https://oss.sonatype.org/content/repositories/snapshots/works/worace/circe-geojson-core_2.12/ that there are a lot of these versions like `0.0.0+100-ec795381-SNAPSHOT` etc which have been published. And the publish steps for these are working OK through Github Actions ([example](https://github.com/worace/circe-geojson/runs/543678425?check_suite_focus=true)). I only started running into this when I tried pushing my first real release using a tagged version.

Any chance anyone has run into an issue like this before? Thanks in advance, let me know if I can provide any more info. Also I'm happy to move this over to sbt-sonatype if it ends up being an issue with that plugin instead.

For reference:

* [Repo](https://github.com/worace/circe-geojson)
* [build.sbt](https://github.com/worace/circe-geojson/blob/master/build.sbt)
* [release.yml Github Workflow definition](https://github.com/worace/circe-geojson/blob/master/.github/workflows/release.yml)
* [Failed build log](https://github.com/worace/circe-geojson/runs/574446148?check_suite_focus=true)

**Comment by SethTisue** [comment]
The `0.0.1-CI-2-SNAPSHOT` versus `0.0.1-CI-3-SNAPSHOT` in the log you posted seems like a clue.

This is a fairly random guess, but I wonder if it has do with the `-SNAPSHOT` in the version. If you don't have any better ideas, you might try publishing a non-snapshot and see if it goes through?

I use sbt-ci-release in a bunch of repos, but always with sbt-dynver generated version numbers that never end in `-SNAPSHOT`.

**Comment by worace** [comment]
Wow, that is quite a hunch, because it seems to have worked. I was able to push v0.0.2 here: https://oss.sonatype.org/#nexus-search;quick~works.worace

I see your point about the SNAPSHOT versioning. I imagine in normal practice I would not need SNAPSHOT versions since like you said I should never really need to overwrite them. But because sbt-ci-release only builds tags with `v...` I started using snapshot tags while debugging so that I would avoid "burning" real versions while I was trouble-shooting the CI.

However funnily enough I guess that ended up self-inflicting this problem on me, because somewhere along the way I must have fixed the original issue I started looking at (I think I had something mis-configured in the build.sbt), but because I was now using snapshot tags, I ran into this separate issue.

Anyway, thanks for your suggestion, it seems to be working now.

One other small thing I ran into was an issue with using the release plugin on different sbt sub-projects as separate release steps. At one point I was suspicious that some of my problems were due to the plugin trying to publish the "root" sbt project, so I split out my CI pipeline to only explicitly publish each subproject as its own step (`sbt 'project core' ci-release` first then `sbt 'project jts' ci-release`). However it seems that when running it this way it attempts to republish the first subproject when it runs for the second subproject. So here you can see an example of a run where it succeeded for the first but then failed for the second: https://github.com/worace/circe-geojson/runs/574766302?check_suite_focus=true

The root vs subproject thing turned out to be a red herring, so I have set them back to just running in 1 phase now, but perhaps that will help anyone who runs into the same issue.
