### ISSUE TITLE
Cannot see artifacts on Maven

### ISSUE THREAD

**Issue by pathikrit** [olafurpg/sbt-ci-release#115]
I [switched](https://github.com/pathikrit/better-files/pull/416/files) to sbt-ci-release for better-files and I love it! Thank you for the great work! 

Yesterday, I attempted the first release of better-files v3.9.0 using Travis CI + sbt-ci-release. You can see the release attempt here: https://travis-ci.com/github/pathikrit/better-files/jobs/334182393

But, although I see the [snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/github/pathikrit/better-files_2.12/) from sbt-ci-release, I do not see the 3.9.0 release in the [artifacts](https://repo1.maven.org/maven2/com/github/pathikrit/better-files_2.12/). I know it takes a while to show up in Maven Central but its been 24 hours. Did this work as expected? If yes, close this issue.

PS: I wrote a [StackOverlow Q&A](https://stackoverflow.com/questions/45963559/how-to-release-a-scala-library-to-maven-central-using-sbt) few years ago about how to release to Maven but IMO you should post a new answer with sbt-ci-release as the answer and I can accept it as the correct answer 😜

**Comment by SethTisue** [comment]
looks like it's there now? https://repo1.maven.org/maven2/com/github/pathikrit/better-files_2.12/3.9.0/

**Comment by pathikrit** [comment]
Yup, it's there. Took a while!
