### ISSUE TITLE
Cross Scala versions issue when releasing

### ISSUE THREAD

**Issue by leobenkel** [olafurpg/sbt-ci-release#120]
Hello ! 

First of all, thank you for your work, I have been using your plugin for years.
But for the first time, I am attempting to publish a library for 2.11 and 2.12 version of scala.
However, I am encountering an issue:

https://issues.sonatype.org/browse/MVNCENTRAL-5842

The link to the log https://travis-ci.com/github/leobenkel/Laeta/jobs/341233122 

It seems that the 2.11 version publish successfully but do not use the `_2.11` naming convention. And therefore the `2.12` version cannot be submitted because it already exists. 

Am I missing some kind of configuration ? https://github.com/leobenkel/Laeta/blob/master/build.sbt ? 

Thank you !

**Comment by leobenkel** [comment]
I also look into https://oss.sonatype.org/#view-repositories;releases~browsestorage~com/leobenkel and all the binaries seem to be there

**Comment by olafurpg** [comment]
Thank you for reporting! Please reopen if this is still an issue.
