### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by susuro** [olafurpg/sbt-ci-release#128]
Hi,

`sbt-ci-release` is a very useful plugin. Thank you for providing it.
There is no license file attached to it, however. Would it be possible to provide one? It could matter for many adopters.

Thank you in advance

**Comment by olafurpg** [comment]
Thank you for reporting! I added the Apache 2 license file into the repo. Note that the published artifacts have always been Apache 2 https://github.com/olafurpg/sbt-ci-release/blob/631189a84edadc9256e63112b11e78546f2382a6/build.sbt#L6
