### ISSUE TITLE
Question: is it possible to override the version used? 

### ISSUE THREAD

**Issue by leobenkel** [olafurpg/sbt-ci-release#142]
Hello ! 

I would like to have a two part version number, like `dependency-version_my-version` like other libraries do. 

How can I override the version number ? 

Thanks.

**Comment by olafurpg** [comment]
Thank you for reporting! You can define `version :=` any way you like. By default, the version number is provided by https://github.com/dwijnand/sbt-dynver There's nothing specific about sbt-ci-release, you can look at the source code yourself, it's only 170 lines https://github.com/olafurpg/sbt-ci-release/blob/master/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala

**Comment by olafurpg** [comment]
If you want to prepend a prefix to the version you can do
```scala
version ~= { oldVersion =>
  "new-suffix_" + oldVersion
}
```

FWIW, the idiomatic way to cross-build against multiple version of a single dependency is to include that name in `moduleName` instead of `versions`

**Comment by leobenkel** [comment]
I copied the way https://mvnrepository.com/artifact/com.holdenkarau/spark-testing-base is doing it. And it works now :) https://github.com/leobenkel/ZparkIO/blob/3c01b7e3ba20391e096588aca9cfe26f52eca7cb/build.sbt#L32-L33 , thank you !
