### ISSUE TITLE
Got a 'gpg-agent is not available in this session' when pushing a tag

### ISSUE THREAD

**Issue by loicknuchel** [olafurpg/sbt-ci-release#149]
Hi!
I'm very new to publishing libs and I really want to thank you for your plugin and documentation, it has been really easy since the beginning.
Sadly, I hit a problem just before the finish line. Everything should be in place but I got a `gpg-agent is not available in this session` error from travis. From the error message, it seems that I missed a travis configuration but can't find it.

Do you know this kind of error ?

If you want to look into my build: https://travis-ci.com/github/loicknuchel/SafeQL/jobs/419279576

Thank you very much.

**Comment by olafurpg** [comment]
Thank you for reporting! It may be that the latest Travis machines use gpg v2 when v1.4 is currently required. If it’s possible, I would recommend trying to release from GitHub actions using the same workflows as this repo.

**Comment by loicknuchel** [comment]
Ok thanks, I will look into this (sadly travis error is not very clear ^^)

**Comment by olafurpg** [comment]
See https://github.com/olafurpg/sbt-ci-release/issues/95 for a related discussion (I'm not 100% sure this is the same issue, but suspect it is related)

**Comment by alexarchambault** [comment]
FYI, when you look at line 393 of the output of your job, sbt-sonatype says
```text
Failed: signature-staging, failureMessage:No public key: Key with id: (e6b067a07e1dfd71) was not able to be located on <a href="http://pool.sks-keyservers.net:11371/">http://pool.sks-keyservers.net:11371/</a>. Upload your public key and try the operation again.
```

It sometimes happens to me on new projects. It seems Sonatype looks for the key on different servers, here `http://pool.sks-keyservers.net:11371` instead of `http://keyserver.ubuntu.com:11371` mentioned in the README of sbt-ci-release.

Usually, uploading the key on the server printed in the error fixes the error for me.

**Comment by loicknuchel** [comment]
Hi!
Thanks for your replies. It works now, and I didn't change anything.
So my guess is that it took time to deploy the key or setup everything.
I still have the `[error] gpg: gpg-agent is not available in this session` so I think it's not very relevant here.

Thanks again, have a nice day.

**Comment by asakaev** [comment]
```
[error] gpg: gpg-agent is not available in this session
[error] gpg: gpg-agent is not available in this session
[error] gpg: gpg-agent is not available in this session
[error] gpg: gpg-agent is not available in this session
```

https://github.com/asakaev/leftpad/runs/1436631932?check_suite_focus=true#step:5:266

@olafurpg  Maybe there is a way to configure pgp to hide these reports?
