### ISSUE TITLE
Can not publish to https://s01.oss.sonatype.org

### ISSUE THREAD

**Issue by sagifogel** [olafurpg/sbt-ci-release#196]
Hi,

I'm having trouble deploying to [https://s01.oss.sonatype.org.](https://s01.oss.sonatype.org)
I performed all the steps several times. I checked the passwords several times.
I tried to use `Access User Token` and also failed (I got different error when I used `Access User Token`).

I also tried using these lines:
ThisBuild / sonatypeProfileName: = "io.github.sagifogel"
ThisBuild / sonatypeCredentialHost: = Sonatype.sonatype01
ThisBuild / sonatypeRepository: = s "https: // $ {Sonatype.sonatype01} / service / local"

But somehow the default sonatype repository https://oss.sonatype.org/service/local is used.
I get different errors when I create a tag and when I do not create a tag.

[Tag](https://github.com/sagifogel/Proptics/runs/2484019050?check_suite_focus=true)
[Snapshot](https://github.com/sagifogel/Proptics/runs/2486743842?check_suite_focus=true)

I was trying to check parts of the code to figure out what I was doing wrong and came across the `buildSettings` variable

```scala
override lazy val buildSettings: Seq[Def.Setting[_]] = List(
    dynverSonatypeSnapshots := true,
    scmInfo ~= {
      case Some(info) => Some(info)
      case None =>
        import scala.sys.process._
        val identifier = """([^\/]+?)"""
        val GitHubHttps = s"https://github.com/$identifier/$identifier(?:\\.git)?".r
        val GitHubGit   = s"git://github.com:$identifier/$identifier(?:\\.git)?".r
        val GitHubSsh   = s"git@github.com:$identifier/$identifier(?:\\.git)?".r
        try {
          val remote = List("git", "ls-remote", "--get-url", "origin").!!.trim()
          remote match {
            case GitHubHttps(user, repo) => Some(gitHubScmInfo(user, repo))
            case GitHubGit(user, repo)   => Some(gitHubScmInfo(user, repo))
            case GitHubSsh(user, repo)   => Some(gitHubScmInfo(user, repo))
            case _                       => None
          }
        } catch {
          case NonFatal(_) => None
        }
    }
  )
```

When I query github for the remote repository I get this:

![image](https://user-images.githubusercontent.com/187556/116817933-70612180-ab71-11eb-9c0d-3d7e7d00b547.png)

Which is a different pattern than the ones in the pattern match `remote match`. 
Is this really a problem? Could this be part of my problem?

This is my [repository](https://github.com/sagifogel/Proptics) 
This is my [sonatype jira](https://issues.sonatype.org/browse/OSSRH-66317?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel) ticket

Thank you very much.

**Comment by blast-hardcheese** [comment]
For others who encounter this, my problem was that I had not run `clean` whilst trying to get my sonatype credentials correct. As a result, I was just reusing the same cached result from when my `sonatypeSessionName` was incorrectly set, which meant nothing I did actually changed the result.

I opened https://github.com/xerial/sbt-sonatype/pull/248 to try and prevent this in the future.
