### ISSUE TITLE
java.io.IOException: Unauthorized when publishing snapshot

### ISSUE THREAD

**Issue by kubukoz** [olafurpg/sbt-ci-release#22]
My apologies if this is an issue unrelated to the plugin. If you decide so, feel free to close.

I tried publishing a few times, having ensured that the env properties in Travis are configured properly (I believe they are - even though I use a *username* to log in, and the readme mentions the email - I tried both but in the UI I use the username), but I'm always stuck at the step of sending the pom/jars:

```
[info] Packaging /home/travis/build/kubukoz/tagless-slick/core/target/scala-2.12/tagless-slick-core_2.12-9877d7d8-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[error] java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/com/kubukoz/tagless-slick-core_2.12/9877d7d8-SNAPSHOT/tagless-slick-core_2.12-9877d7d8-SNAPSHOT.pom was refused by the server: Unauthorized
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:366)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
...
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (core / publish) java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/com/kubukoz/tagless-slick-core_2.12/9877d7d8-SNAPSHOT/tagless-slick-core_2.12-9877d7d8-SNAPSHOT.pom was refused by the server: Unauthorized
```

One of my colleagues suggested to switch from openjdk to oraclejdk because of a possibility of missing certificates, and I did, but it didn't change anything.

Would you know of any way to fix this?

I tried these version configs:

scala | sbt | sbt-ci-release
------|---------|-------------
2.12.7 | 1.2.3 | 1.2.1
2.12.6 | 1.1.6 | 1.1.2

**Comment by olafurpg** [comment]
Thanks for reporting! Can you reproduce by publishing the snapshot from your local machine with "sbt publish"? What if the version number if 0.1.0-SNAPSHOT? Also, please try 1.2.2 that changed the sbt settings to overwrite on publish.

**Comment by kubukoz** [comment]
Hi, thanks for taking a look at this! I updated to 1.2.2 (didn't help, unfortunately), and tried publishing 0.1.0 by tag (so a full blown release), as well as another `0.1.0-hash-SNAPSHOT` *but* by merging a PR (I previously tried making snapshots by pushing straight to master, not sure if there's a difference but that's what you mentioned in the README). Sadly, to no avail :/

I'll try the local machine in the evening, but I'm not looking forward to it as the last time I had issues with incompatibilities of the old and new gpg keyring format.

**Comment by olafurpg** [comment]
Have you double triple checked the SONATYPE_USERNAME and SONATYPE_PASSWORD environment variables?

> I'll try the local machine in the evening, but I'm not looking forward to it as the last time I had issues with incompatibilities of the old and new gpg keyring format.

You don't need pgp setup to publish snapshots. `sbt publish` is enough, it's only stable releases that require `publishSigned` that calls pgp.

**Comment by kubukoz** [comment]
I got it!

Apparently having special characters in a password requires escaping, but I was wrapping the whole string in `"`, whereas it's single quotes (`'pass?word'`). So, yeah, I'm publishing artifacts now - thanks a lot!

**Comment by olafurpg** [comment]
Glad it worked out! I updated the readme to mention escaping of special characters in SONATYPE_PASSWORD f5db3c93c2d36f27c75487649dc16dab862bbbca and also added an entry in the FAQ including the error message b7b2a41bba987083a71feffc184704370faf9151
