### ISSUE TITLE
"Multiple repositories are found" problem

### ISSUE THREAD

**Issue by kubukoz** [olafurpg/sbt-ci-release#27]
I'm getting this when making a release for the first time (attempting to publish 2 sbt subprojects across 2 scala versions). Is this an issue with sbt-ci-release, or should I bug someone else? Possibly related to #11.

Note: I made sure to remove all staging repositories before trying to publish.

Here's the error I'm getting:

```
[error] Multiple repositories are found:
[error] [com[secure]-1046] status:open, profile:com.[secure](3cd6b19d807dd3) description: Implicitly created (auto staging).
[error] [com[secure]-1047] status:open, profile:com.[secure](3cd6b19d807dd3) description: Implicitly created (auto staging).
[error] [com[secure]-1048] status:open, profile:com.[secure](3cd6b19d807dd3) description: Implicitly created (auto staging).
[error] Specify one of the repository ids in the command line
[error] java.lang.IllegalStateException: Found multiple staging repositories
```

Edit: I looked at the contents of these staging repositories, and the first two contain one subproject each (2.11), whereas the third one contains both 2.12-compiled subprojects.

**Comment by olafurpg** [comment]
This error is expected when you have multiple open sonatype repositories. ci-release runs `sonatypeRelease` by default instead of `sonatypeReleaseAll` to avoid accidental publishing. You can ignore the error and manually run `sonatypeReleaseAll` if that was intended.

**Comment by kubukoz** [comment]
Could it be made so that ci-release releases only the repositories that it opened? With the current behavior, I assume it's impossible to have a fully automated multi-project publish :(

btw. thanks for the prompt response!

**Comment by olafurpg** [comment]
I use `ci-release` in multi-project cross-built cross-platform builds and it only creates one staging repository. I would try to understand why it creates multiple repos in your case (parallel jobs?).


One option is to allow users to run `sonatypeReleaseAll` through a setting, relevant line https://github.com/olafurpg/sbt-ci-release/blob/11e326b1c33f6f45002807f46524bda960e39b3d/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L67
Beyond that, I believe we're blocked by sbt-sonatype.

**Comment by olafurpg** [comment]
I think `sonatypeRelease` is a safe default because at worst it fails the publish, whereas `sonatypeReleaseAll` can at worst publish unintended artifacts.

**Comment by kubukoz** [comment]
Yeah, I'm pretty sure I don't want to use `sonatypeReleaseAll` and risk unintended publishing. I don't have any parallel jobs, so I guess there's something sketchy with my build :P

**Comment by olafurpg** [comment]
I'm afraid there's not much we can do about this in sbt-ci-release. When I enounter "Found multiple staging repositories" in CI I manually run `sbt sonatypeDrop/sonatypeRelease` from my computer.
