### ISSUE TITLE
Need an easy way to cross publish versions of Scala.js and Scala Native

### ISSUE THREAD

**Issue by ekrich** [olafurpg/sbt-ci-release#42]
This project takes an opinionated way to publish using `sbt-crossproject` and Travis CI. This is super great as it helps non-experts actually publish. I have 2 projects, one that only does Scala Native but CI builds on Mac and Linux and one that does multiple Scala Versions plus Scala Native and Scala.js respectively as listing below. 

For Reference:
https://github.com/ekrich/sblas
https://github.com/ekrich/sconfig

I would like to take this to the next step and provide `build.sbt` and `travis.yml` to have different versions of Scala Native, 0.3.x and 0.4.x and Scala.js 0.6.x and 1.0.x. Here the plugin version matters.

The following project builds for cross project and Scala.js versions. The `project/plugins.sbt` file uses an environment variable and default to get the correct version. Travis sets this variable and the `travis.yml` uses a traditional matrix versus stages used in `sbt-ci-release`. Using Travis this way is easy to understand but also lists all the versions in CI and well as in the build which is duplication but adding a new Java version is easy but would double the number of runs as well without excludes. `sbt` is also executed over and over as well.

https://github.com/portable-scala/portable-scala-reflect

Looking for guidance but could also help as well. My initial thought was to add an additional subproject for both Native and JS to allow 2 versions of each but handling the plugin version change is unknown. The other approach is maybe a hybrid of the above using the env vars but then stages like this project.

**Comment by olafurpg** [comment]
Thanks for reporting! The `CI_RELEASE` environment variable controls what command to run for `+publishSigned`, see https://github.com/olafurpg/sbt-ci-release#travis. You can customize this variable to run publish for a single project like `export CI_RELEASE="+coreJS/publishSigned"` to skip the publish in non-JS projects. The same applies to native. Does that help?

**Comment by olafurpg** [comment]
To clarify, the release will require multiple `sbt ci-release` steps with different environment variables, something like this
```sh
sbt ci-release # default release
export SCALAJS_VERSION=1.0.0
export CI_RELEASE="+coreJS/publishSigned"
sbt ci-release # Scala.js v1 release
export NATIVE_VERSION=0.4.0
export CI_RELEASE="+coreNative/publishSigned"
sbt ci-release # Native v0.4 release
```

**Comment by ekrich** [comment]
This helps me quite a bit. The beauty of the current setup and example is that the build is called once for cross build and then release is called and all artifacts are published. If we want to build for the additional Scala.js or Scala Native platforms we could do a Travis Matrix approach like in the `portable-scala-reflect` above and build an additional 2 times, once each for the additional JS and Native and then call the additional publish steps as you recommend. 

It seems there is no way to build all and then publish all even if you call the build step additional times?

Let me see if I can come up with a good approach/example and then I can do a PR to add some documentation about the approach to close this issue.

**Comment by olafurpg** [comment]
Closing as wontfix. You are still welcome to open a PR if you think the current implementation or documentation can be improved to cater this use-case.

sbt-ci-release can only abstract over the publish step in a single sbt JVM process. Another possible workaround to release all versions in one step is to

```sh
export CI_SONATYPE_RELEASE=version # dummy placeholder to skip `sonatypeRelease` step
sbt ci-release # default release
export SCALAJS_VERSION=1.0.0
export CI_RELEASE="+coreJS/publishSigned"
sbt ci-release # Scala.js v1 release
export NATIVE_VERSION=0.4.0
export CI_RELEASE="+coreNative/publishSigned"
sbt ci-release # Native v0.4 release
sbt sonatypeReleaseAll # should be skipped when publishing SNAPSHOT
```
I haven't tried this however.
