### ISSUE TITLE
[Suggestion] README change - name tasks

### ISSUE THREAD

**Issue by leobenkel** [olafurpg/sbt-ci-release#43]
In the README it says to use `env TEST="<name>"` but you can actually just use `name` as in here https://github.com/leobenkel/safety_plugin/blob/15ce058cfa40611d909b7cb3c4245e3b6ff63056/.travis.yml#L24 for instance

**Comment by olafurpg** [comment]
Cool! I didn't know about this, you are welcome to send a PR changing the docs 😉

**Comment by leobenkel** [comment]
done
