### ISSUE TITLE
Issue with "No staging repository is found"

### ISSUE THREAD

**Issue by leobenkel** [olafurpg/sbt-ci-release#44]
Hello,
I am having an issue with my pipeline. I am trying to release the very first version of my plugin but I am getting: 

```
java.lang.IllegalStateException: No staging repository is found. Run publishSigned first
```

Links:
* https://github.com/leobenkel/safety_plugin
* https://travis-ci.org/leobenkel/safety_plugin

**Comment by leobenkel** [comment]
From https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html#sbt-sonatype , it seems that running 
```
sonatypeOpen "your groupId" "Some staging name"
```

before `publishSigned` is required

**Comment by leobenkel** [comment]
More clues: https://oss.sonatype.org/content/repositories/staging/com/leobenkel/safety_plugin_2.12_1.0/ the staging folder seem to be there

**Comment by olafurpg** [comment]
Thanks for reporting! What is the output of “show organization”?

**Comment by leobenkel** [comment]
`com.leobenkel` as expected from https://github.com/leobenkel/safety_plugin/blob/25539b632bf885734cda0156f01f44b25fdd96b9/project.sbt#L3

**Comment by leobenkel** [comment]
One PR merge is running right now: https://travis-ci.org/leobenkel/safety_plugin/builds/544860116 And I will mark this commit as a new tag to try again when thats finish

**Comment by leobenkel** [comment]
so it is in staging and snapshot: https://oss.sonatype.org/content/repositories/staging/com/leobenkel/safety_plugin_2.12_1.0/ 

https://oss.sonatype.org/content/repositories/snapshots/com/leobenkel/safety_plugin_2.12_1.0/

**Comment by leobenkel** [comment]
going to run 
```
git tag -a $(VERSION) -m $(VERSION)
git push origin $(VERSION)
```

locally now and see how it goes

**Comment by leobenkel** [comment]
running with the tag: 
https://travis-ci.org/leobenkel/safety_plugin/builds/544870243

**Comment by leobenkel** [comment]
it is on the same commit hash ` 25539b6 ` . but it is not a problem, right ? How would you do it otherwise?

**Comment by leobenkel** [comment]
It said it succeed but there is nothing in https://repo1.maven.org/maven2/com/

**Comment by leobenkel** [comment]
I'm lost. I dont know what is wrong.

**Comment by leobenkel** [comment]
there are no errors anymore

**Comment by leobenkel** [comment]
the latest staging folder is there https://oss.sonatype.org/content/repositories/staging/com/leobenkel/safety_plugin_2.12_1.0/88-25539b63-SNAPSHOT/ but it seems that it did not publish the right one

**Comment by leobenkel** [comment]
I see 

```
[info] Closing staging repository [comleobenkel-1000] status:open, profile:com.leobenkel(b65f58f0ed3617) description: com.leobenkel
``` 
in the log of https://travis-ci.org/leobenkel/safety_plugin/jobs/544870249

which is the staging repo created from the command:
```
sbt "sonatypeOpen com.leobenkel"
```

`comleobenkel-1000` , I was also able to see it in the webUI : https://oss.sonatype.org/#stagingRepositories

But after the travis job ran, it is not in the list anymore. 

So I suspect that this repo was deployed as release but it did not contained anything , no files.
It feels that the plugin is missing to assign the https://oss.sonatype.org/content/repositories/staging/com/leobenkel/safety_plugin_2.12_1.0/88-25539b63-SNAPSHOT/ as the staging repo to release.

**Comment by leobenkel** [comment]
No idea what that means but when i go to https://oss.sonatype.org/ , then to 

`Repositories` -> double click on `Staging` -> in the menu below -> tab `Browse Storage` -> `com.leobenkel` is there.

but in :
`Repositories` -> double click on `Staging` -> in the menu below -> tab `Browse Index` -> `com.leobenkel` is *not* there.

**Comment by leobenkel** [comment]
@olafurpg would you be able to take a look ? I asked on [stackoverflow](https://stackoverflow.com/questions/56587653/issue-with-no-staging-repository-found-in-sonatype-publish), even added a bounty, as well as asked on [Reddit](https://www.reddit.com/r/scala/comments/c11j8o/anyone_have_published_to_sonatype_before_i_am/) but nobody seem to know the answer.

**Comment by olafurpg** [comment]
Have you tried running the release steps manually from sbt on your local computer? First “publishSigned” and then “sonatypeRelease”. I recommend using “sonatypeDrop” if you have any existing open repositories, which you can list with “sonatypeStagingRepositoryProfiles” (might be a typo somewhere I’m on a phone).

**Comment by leobenkel** [comment]
Thank you for your answer @olafurpg .

`sonatypeStagingRepositoryProfiles ` is returning:
```
[info] Reading staging repository profiles...
[warn] No staging repository is found. Do publishSigned first.
[warn] No staging repository is found for com.leobenkel
```
and no typo ! Congratz from your phone ! haha.

locally `publishSigned` return:

```
[error] java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
```

And I can't find a way to solve this issue. I followed the steps from https://github.com/olafurpg/sbt-ci-release#gpg 

And as expected `sonatypeRelease` return:
```
[info] sonatypeProfileName = com.leobenkel
[info] Reading staging repository profiles...
[warn] No staging repository is found. Do publishSigned first.
[info] Reading staging profiles...
[error] java.lang.IllegalStateException: No staging repository is found. Run publishSigned first
```

**Comment by olafurpg** [comment]
It looks like the publishSigned step failed, which might be caused by the
gpg installed on your computer. Please check the sbt-pgp docs. What version
of gpg do you have installed?

**Comment by leobenkel** [comment]
```
▶ gpg --version
gpg (GnuPG) 2.2.16
libgcrypt 1.8.4
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/lbenkel/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

But this step seem to work from Travis.

**Comment by olafurpg** [comment]
Here's my output, looks similar
```
$ gpg --version
gpg (GnuPG) 2.2.10
libgcrypt 1.8.4
```

Judging by the logs, it looks like you are publishing a SNAPSHOT version successfully but it's triggering a stable release. The tag is named "0.1", can you try again with "v0.1" (observe the leading `v`).

**Comment by leobenkel** [comment]
ok, I am trying with `v0.1` , here is the Travis link: https://travis-ci.org/leobenkel/safety_plugin/builds/547311804 

omg I think it worked ! WTF!? Why does it fail if it does not start by `v` ?! 

Thank you so much for your help !

**Comment by leobenkel** [comment]
I was able to fetch the library from a local project so it all worked ! Thanks !

**Comment by olafurpg** [comment]
> omg I think it worked ! Why does it fail if it does not start by v ?!


I believe this is related to how sbt-dynver works 🤔 Reopening since this is still a bug in sbt-ci-release since we publish a SNAPSHOT release and then try to run `sonatypeRelease`

**Comment by olafurpg** [comment]
Glad it worked!
