### ISSUE TITLE
Error, Multiple repositories are found

### ISSUE THREAD

**Issue by ryanstull** [olafurpg/sbt-ci-release#48]
I'm trying top cross-build a project for scala 2.11, 2.12, and 2.13

The project is here https://github.com/ryanstull/ScalaNullSafe

When the build script runs on travisCI, I also get this error:
```
[error] Multiple repositories are found:
[error] [comryanstull-1025] status:open, profile:com.ryanstull(9dd2c8b46008f8) description: Implicitly created (auto staging).
[error] [comryanstull-1026] status:open, profile:com.ryanstull(9dd2c8b46008f8) description: Implicitly created (auto staging).
[error] [comryanstull-1027] status:open, profile:com.ryanstull(9dd2c8b46008f8) description: Implicitly created (auto staging).
```
`sbt-ci-release` is pushing each different version to a separate sonatype repo, and then when it tries to publish to the main repo, it gets confused.

Here's the full log from TravisCI: https://gist.github.com/ryanstull/83e7578ef933dbfeafb161b89d87ad42

build.sbt: https://github.com/ryanstull/ScalaNullSafe/blob/master/build.sbt
.travis.yml: https://github.com/ryanstull/ScalaNullSafe/blob/master/.travis.yml

Is there a setting I can change to make all of the different versions go into the same repo?  Any help would be appreciated.

**Comment by olafurpg** [comment]
Thanks for reporting! This is working as expected, sbt-ci-release defaults on the safe side and tries only to release a single staging repository or fail if there are multiple. You can configure `export CI_SONATYPE_RELEASE=sonatypeReleaseAll` to release all staging repositories.

<img width="907" alt="Screenshot 2019-06-25 at 08 59 54" src="https://user-images.githubusercontent.com/1408093/60076395-bc4a1080-9727-11e9-84f6-c1cfbb71d5bf.png">

Note that you can run `sonatypeReleaseAll` from your local sbt shell or `sonatypeDrop` (to remove the staging repos).

I have never fully understood when `publishSigned` chooses to open new staging repositories vs. reusing existing ones. I really wish it behaved the same way as in `mill publish` where each publish step opens/closes its own staging repositoriy.

**Comment by olafurpg** [comment]
The reason `sonatypeReleaseAll` is not the default is because it can publish half-complete staging repositories when publishing from parallel jobs.

**Comment by olafurpg** [comment]
I'm not sure why `publishSigned` would create multiple staging repositories for the ScalaNullSafe build since it only has one project with multiple `crossScalaVersions`. I use the same setup in large multi-module, multi-platform and cross-scala version builds and it still only opens a single staging repository 🤔

**Comment by ryanstull** [comment]
Thanks for the quick reply!  I'll try that out

**Comment by ryanstull** [comment]
It seems that adding `export CI_SONATYPE_RELEASE=sonatypeReleaseAll` did not fix the issue.

https://gist.github.com/ryanstull/84700a7b77497cbcb0913f0f86106a45

**Comment by olafurpg** [comment]
This environment variable is used here 
https://github.com/olafurpg/sbt-ci-release/blob/9c1513d48e7dc0d3294ec3183839d45b8fba3c3d/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L92

What version of sbt-ci-release are you using?

What happens if you run `sbt sonatypeReleaseAll` from your local computer?

**Comment by ryanstull** [comment]
Looks like updating to the latest version of `sbt-ci-release` fixed this.  Before I was on `1.2.2` and it worked after changing to `1.2.6`, in combination with defining `CI_SONATYPE_RELEASE=sonatypeReleaseAll`.

Thanks for the help!
