### ISSUE TITLE
Sonatype Bundle Release

### ISSUE THREAD

**Issue by ChristopherDavenport** [olafurpg/sbt-ci-release#58]
sbt-sonatype 3.4 launched with a pretty new feature called `sonatypeBundleRelease`. Rather than putting all artifacts up individually posts them as a bundle. 

As CI time publishing large libraries can take a very long time when sonatype is slow and travis has timeouts on both no output and an hour long run, it would be advantageous if this was default here.

**Comment by tpolecat** [comment]
I tried this and I'm confused as hell. I'll open a PR.
