### ISSUE TITLE
pgpSecretRing points to wrong file if not cross-building

### ISSUE THREAD

**Issue by lrytz** [olafurpg/sbt-ci-release#64]
This issue is basically the same as reported in https://github.com/olafurpg/sbt-ci-release/issues/26, but I figured out what's going on.

The `~/.gnupg/secring.gpg` file is created in the sbt session. So when sbt is started, the file doesn't exist yet. Because the file doesn't exist, [pgpSecretRing](https://github.com/sbt/sbt-pgp/blob/209e33c3ddec54f0857081db33cba81feb1880de/pgp-plugin/src/main/scala/com/typesafe/sbt/pgp/PgpSettings.scala#L106-L109) points to `~/.sbt/gpg/secring.asc`.

When cross-building (`CI_RELEASE=+publishSigned`), sbt reloads the build for every Scala version (not sure if "reload" is the right technical term here), settings are re-evaluated. Because `~/.gnupg/secring.gpg` now exists, `pgpSecretRing` gets the correct value.

If `CI_RELEASE=publishSigned`, the relaod doesn't happen.

**Comment by olafurpg** [comment]
Looks worth a try! Can you send a PR?
