### ISSUE TITLE
[Idea] Automatic changelog generation/management

### ISSUE THREAD

**Issue by jatcwang** [olafurpg/sbt-ci-release#77]
Hi I'd like to start a conversion regarding automanagement of changelogs and whether this project can support one of them.

There are a few options:

* Git Annotated Tag
* manually updated CHANGELOG.md (i.e. updated in every PR)
* Automatically generated CHANGELOG.md from commit messages

Using git annotated tag is nice because the github UI shows it, but it is harder to see what changes has happened since the last released version.

I personally like manually written `CHANGELOG.md` that's done in every PR with user-facing change. In https://github.com/mdsol/sbt-smartrelease/, once a release is made CI will automatically update `CHANGELOG.md` with the version that was just released. ([Example](https://github.com/mdsol/sbt-smartrelease/commit/0bf322790b7f79540c8723792df92149d05c7440)). Also, I think this approach can be combined with Git Annotated Tag so the end user can still easily find the change log.

(Haven't had much experience with the third, but I feel that commit messages don't normally make good release notes)

**Comment by olafurpg** [comment]
Thank you for reporting! Have you looked at release drafter? https://github.com/apps/release-drafter

I believe this feature is outside the scope of this project. My personal opinion is that writing release notes requires manual work and should not be automated. The Release Drafter application however helps you write up most of the boilerplate.

**Comment by jatcwang** [comment]
I agree that it should be a manual process. No I was not aware of it thanks! (So that's how you guys are creating the nice release notes! :open_mouth: ) I think that should solve most of my problems then!

**Comment by olafurpg** [comment]
It would be a good idea to mention release drafter in the readme. If you want to submit a pr ;)
