### ISSUE TITLE
[Idea] Binary compatibility check

### ISSUE THREAD

**Issue by jatcwang** [olafurpg/sbt-ci-release#78]
Binary compatibility is important for Scala libs and currently everyone is doing their own setup. I think this plugin can provide a good default to help catch unexpected breakages. By making version number representative of binary compatibility, day-to-day life will be much nicer for a Scala dev (e.g. by using https://www.scala-lang.org/2019/10/17/dependency-management.html)

There are two approaches:

* Restrictive: Enforce that binary compatibility is never broken - This is the approach taken by cats since they don't want to break compatibility in most cases
* Permissive: Inform the library author in CI that binary compatibility has been broken. This is the approach taken by https://github.com/mdsol/sbt-smartrelease and works well for libraries that aren't heavily dependent on. (But a good versioning scheme will still help your users catch binary incompatible versions)

We can implement both and the user can choose what makes senes for their library. WDYT?

**Comment by olafurpg** [comment]
Thank you for reporting! I believe that MiMa is the is best way to enforce binary compatibility. I’m not sure how much this plugin can help improve the situation besides automatically adding a dependency on sbt-mima 🤔

**Comment by ChristopherDavenport** [comment]
I created sbt-mima-version-check for this reason.

**Comment by olafurpg** [comment]
@ChristopherDavenport thank you for sharing! I believe binary compatibility checking is outside the scope of this project. I'm happy to merge a PR adding a note/link under the FAQ section recommending an sbt plugin like sbt-mima-version-check to verify binary compatibility between releases.
