### ISSUE TITLE
Problem with cross-build release

### ISSUE THREAD

**Issue by ekrich** [olafurpg/sbt-ci-release#87]
Versions: the plugin version below and sbt `1.3.2` and `1.3.5`.
```Scala
addSbtPlugin("com.geirsson" % "sbt-ci-release"  % "1.4.31")
```

I am having a problem where the release gets staged but cannot release. In Sonatype I see the following so I guess I am getting duplicates:
```
  | Artifact  updating: Repository ='releases:Releases' does not allow updating  artifact='/org/ekrich/sconfig_sjs0.6_2.12/1.1.2/sconfig_sjs0.6_2.12-1.1.2-sources.jar'
```
<img width="257" alt="image" src="https://user-images.githubusercontent.com/933058/70840090-f043eb80-1dc4-11ea-857a-9dc853c263eb.png">

I guess the staging repo went away as I can't find it anymore. I tried to re-release like above but it failed - I told it to keep the staging artifact but it dumped them I guess.

Here are the failures in CI.
https://travis-ci.org/ekrich/sconfig/builds

Last part of the build listed here - tons of warnings as I need to fix the Scaladoc - sorry.

```
[info] Promoting staging repository [org[secure]-1023] status:closed, profile:org.[secure](6b2912b5a0fa66) description: [sbt-sonatype] sconfig-root 1.1.2
[info] Activity release started:2019-12-13T22:54:15.189Z, stopped:
[info]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy
[info]   Evaluate: RepositoryWritePolicy
[info]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/org/[secure]/sconfig_2.11/1.1.2/sconfig_2.11-1.1.2.pom'
[info]     Failed: id:nx-internal-ruleset, failureCount:1
[error] Failed to promote the repository
[error] Activity release started:2019-12-13T22:54:15.189Z, stopped:
[error]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/org/[secure]/sconfig_2.11/1.1.2/sconfig_2.11-1.1.2.pom'
[error] java.lang.Exception: Failed to promote the repository
[error] Use 'last' for the full log.
restoring stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
The command "sbt ci-release" exited with 1.
```
So this seems like I am getting a duplicate artifact or something.

The last time cross publish worked was when I published `1.0.0` which included an extra Scala Native `0.4.0-M2` but no extra Scala.js. See https://github.com/ekrich/sconfig/tree/v1.0.0
```yaml
script:
    - sbt ci-release
    - export SCALANATIVE_VERSION=0.4.0-M2
    - export CI_RELEASE="+sconfigNative/publishSigned"
    - sbt ci-release
```
The versions then was `addSbtPlugin("com.geirsson" % "sbt-ci-release"  % "1.2.6")` and sbt was `sbt.version=1.2.8`.

All the versions get deployed using overwriting type SNAPSHOTS - without hash or timestamp.

**Comment by olafurpg** [comment]
Thank you for reporting! What happens if you upgrade to the latest sbt-ci-release and retu with a new version number? You might also want to drop all open staging repos that didn’t close.

**Comment by ekrich** [comment]
I am using 1.4.31 so I believe that is the latest. It seems that the staging repos get closed automatically as in this info from Sonatype. Is that correct?

> Note that deploying with the Nexus Staging Maven plugin or Ant tasks will, by default, automatically attempt to close the staging repository upon deployment and can be used to release the staging repository from the command line as well. This allows you to avoid logging into the OSSRH user interface altogether. More details can be found in the Maven and Ant sections of this guide.

I found one thing looking at the **Staging** https://oss.sonatype.org/content/groups/staging/ on the main page and browsing to `org.ekrich` 

![image](https://user-images.githubusercontent.com/933058/70928498-054b9500-1fe6-11ea-92ac-5ca07822631b.png)

This is the only thing there and I can't seem to delete them - not sure what that is or why it is there. All the **Staging Repositories** are gone at this point. I tagged `1.1.0, 1.1.1, and 1.1.2` and none of them worked fully.

I can try a new tag but I am a bit gun shy now that they have not been working.

**Comment by ekrich** [comment]
Could the last comment here might be a player? I can paste the comment in here if you prefer.
https://issues.sonatype.org/browse/OSSRH-42678

**Comment by ekrich** [comment]
I have done some work to clean up the logs by fixing scaladoc generation.

Does there perhaps need to to be a semicolon in front and between the sbt commands?
https://travis-ci.org/ekrich/sconfig/jobs/628946788

Latest release - note that Dotty (JVM) gets run again.
https://travis-ci.org/ekrich/sconfig/jobs/628946788

**Comment by ekrich** [comment]
Setting the `CI_RELEASE` does not seem to work correctly as the JVM bits get published.
https://travis-ci.org/ekrich/sconfig/jobs/629172724#L1001
Running the commands `;+sconfigNative/publishLocal;+sconfigJS/publishLocal` in sbt work as expected when run locally.

**Comment by ekrich** [comment]
Corrected report. I am using the first suggestion in this report - https://github.com/olafurpg/sbt-ci-release/issues/42 
Current Travis File - https://github.com/ekrich/sconfig/blob/25933448b9b9374133499f12a19b2157c7097742/.travis.yml 
Note: with snapshot releases, the second `ci-release` seem to build everything maybe because the `publishSigned` doesn't make sense.

This approach worked fine until `sbt-ci-release` upgraded to use the new `sbt-sonatype`. The first call to `ci-release` publishes all the normal cross versions. The second call to `ci-release` for the additional JS and Native versions works fine until `sbt-sonatype` finds all artifacts from the first publish in `sonatype-staging` and attempts to publish them again.

1. Easy way - clean the `sonatype-staging` between first and second publish.
2. Better way - allow `ci-release` to avoid the first publish to build up the artifacts and then allow the second call to `ci-release` to gather all the artifacts and publish them.
3. Something better?

The current workaround is to delete all the staged artifacts included in the second release from the first release to allow the second release to pass.

**Comment by olafurpg** [comment]
Thank you for tracking down the issue! I wonder if we can fix the issue by calling `sonatypeBundleClean` before calling `publishSigned` and `sonatypeBundleRelease` 🤔 https://github.com/xerial/sbt-sonatype/#other-commmands

**Comment by olafurpg** [comment]
> Better way - allow ci-release to avoid the first publish to build up the artifacts and then allow the second call to ci-release to gather all the artifacts and publish them.

I think you can already achieve this by setting `CI_SONATYPE_RELEASE` to a no-op command like `version`

**Comment by ekrich** [comment]
I tried doing something like this - https://github.com/ekrich/sconfig/blob/master/.travis.yml
But now nothing is put into `sonatype-staging` but it looks like it just uploads each when doing a SNAPSHOT. See https://github.com/xerial/sbt-sonatype/blob/master/src/main/scala/xerial/sbt/Sonatype.scala#L93-L99

I hate to keep publishing bad versions every time I test - any pointers in this area?

**Comment by olafurpg** [comment]
I opened https://github.com/olafurpg/sbt-ci-release/pull/97 adding an automatic `sonatypeBundleClean` step to `CI_SONATYPE_RELEASE` and added a section in the readme how to configure the CI to release with `SCALAJS_VERSION=0.6.31 sbt ci-release`

**Comment by olafurpg** [comment]
I BTW validated these instructions work in https://github.com/scalameta/munit/commit/c0a318f2e63e23ad44daa961c2ca6f9c0fffc9da/checks?check_suite_id=408844155#step:5:806

I started with `SCALAJS_VERSION=0.6.31 CI_RELEASE="+munitJS/publishSigned" ci-release`, which works OK but it does not scale nicely if you publish multiple JS projects. The `.jvmSettings(skip.in(publish) := customScalaJSVersion.isDefined)` instructions feel nicer IMO
