### ISSUE TITLE
Release of 1.5.1 and 1.5.2 missing from maven

### ISSUE THREAD

**Issue by softinio** [olafurpg/sbt-ci-release#98]
Noticed these two releases but they are not available on maven for me to use. Thought I report in case there was a build issue when released on github. 

cc @olafurpg

**Comment by olafurpg** [comment]
I deleted the tags. There's nothing important in those releases, not sure why they failed yet.

**Comment by softinio** [comment]
100% agreed. Good plan. Thanks Sir.

**Comment by softinio** [comment]
@olafurpg in case you want to look at why they were not published, error details:

```
[error] java.io.IOException: Supplied file /home/runner/work/sbt-ci-release/sbt-ci-release/target/sonatype-staging/1.5.2 is a not an existing directory!
```

<https://github.com/olafurpg/sbt-ci-release/runs/409407217?check_suite_focus=true>

Feel free to close this issue if not needed.

**Comment by olafurpg** [comment]
1.5.2 should be on its way to Maven. I had a bug in the new `sonatypeBundleClean` step
